In [1]:
import pandas as pd

fake = pd.read_csv('data/Fake.csv')
real = pd.read_csv('data/True.csv')

print("Fake shape:", fake.shape)
print("Real shape:", real.shape)

fake.head()

Fake shape: (23481, 4)
Real shape: (21417, 4)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [2]:
print("Real shape:", real.shape)
real.head()

Real shape: (21417, 4)

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [3]:
fake['label'] = 0  # 0 = fake
real['label'] = 1  # 1 = real

df = pd.concat([fake, real], ignore_index=True)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)  # shuffle

print("Combined shape:", df.shape)
df['label'].value_counts()

Combined shape: (44898, 5)

label
0    23481
1    21417
Name: count, dtype: int64

In [4]:
import re

def clean_text(text):
    text = str(text)
    # Remove "CITY (Reuters) -" style datelines
    text = re.sub(r'^.*?\(Reuters\)\s*-\s*', '', text)
    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['clean_text'] = df['text'].apply(clean_text)

# quick check: compare before/after on a couple of rows
df[['text', 'clean_text']].sample(3, random_state=1)

,text,clean_text
4528,An electrical contractor wrote to the 54-year-...,An electrical contractor wrote to the 54-year-...
31727,Wow is right! Tomi Lahren gives the best ever ...,Wow is right! Tomi Lahren gives the best ever ...
10937,Funny how secrets travel. I d start to believ...,Funny how secrets travel. I d start to believe...

In [5]:
# Check specifically on real news rows (label=1) to confirm Reuters prefix is gone
df[df['label']==1][['text', 'clean_text']].sample(3, random_state=1)

,text,clean_text
27824,SYDNEY (Reuters) - Australian Prime Minister M...,Australian Prime Minister Malcolm Turnbull sai...
39188,WASHINGTON (Reuters) - The U.S. budget deficit...,The U.S. budget deficit is projected to rise t...
29302,WASHINGTON (Reuters) - President Donald Trump ...,President Donald Trump visited the Supreme Cou...

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

X = df['clean_text']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train size:", X_train.shape[0])
print("Test size:", X_test.shape[0])

vectorizer = TfidfVectorizer(max_df=0.7, min_df=5, stop_words='english', max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("TF-IDF matrix shape:", X_train_tfidf.shape)

Train size: 35918
Test size: 8980
TF-IDF matrix shape: (35918, 5000)

In [7]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, y_train)

print("Model trained!")

Model trained!

In [8]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9748329621380847

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.97      0.98      4696
           1       0.97      0.98      0.97      4284

    accuracy                           0.97      8980
   macro avg       0.97      0.97      0.97      8980
weighted avg       0.97      0.97      0.97      8980


Confusion Matrix:
 [[4565  131]
 [  95 4189]]

In [9]:
import joblib

joblib.dump(model, 'model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')

print("Model and vectorizer saved!")

Model and vectorizer saved!

In [1]:
welfake = pd.read_csv('data/WELFake_Dataset.csv')
print("WELFake shape:", welfake.shape)
print("\nColumns:", welfake.columns.tolist())
welfake.head()

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

fake = pd.read_csv('data/Fake.csv')
real = pd.read_csv('data/True.csv')

print("Fake shape:", fake.shape)
print("Real shape:", real.shape)

Fake shape: (23481, 4)
Real shape: (21417, 4)

In [3]:
welfake = pd.read_csv('data/WELFake_Dataset.csv')
print("WELFake shape:", welfake.shape)
print("\nColumns:", welfake.columns.tolist())
welfake.head()

WELFake shape: (72134, 4)

Columns: ['Unnamed: 0', 'title', 'text', 'label']

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [4]:
reuters_rows = welfake[welfake['text'].str.contains(r'\(Reuters\)', na=False)]
print("Rows containing '(Reuters)':", len(reuters_rows))
print(reuters_rows['label'].value_counts())

Rows containing '(Reuters)': 21282
label
0    21266
1       16
Name: count, dtype: int64

In [5]:
# Drop the unnamed index column
welfake = welfake.drop(columns=['Unnamed: 0'])

# Flip labels to match our convention: 0=fake, 1=real
welfake['label'] = welfake['label'].map({0: 1, 1: 0})

# Drop rows with missing text (can't train on empty text)
welfake = welfake.dropna(subset=['text'])

print("WELFake after cleanup:", welfake.shape)
print(welfake['label'].value_counts())

WELFake after cleanup: (72095, 3)
label
0    37067
1    35028
Name: count, dtype: int64

In [6]:
# Rebuild original combined df with labels (in case kernel was reset)
fake['label'] = 0
real['label'] = 1
original_df = pd.concat([fake[['title', 'text', 'label']], real[['title', 'text', 'label']]], ignore_index=True)

# Combine original + WELFake
combined = pd.concat([original_df, welfake[['title', 'text', 'label']]], ignore_index=True)

print("Before dedup:", combined.shape)

# Remove exact duplicate articles (same text)
combined = combined.drop_duplicates(subset=['text'])

print("After dedup:", combined.shape)
print(combined['label'].value_counts())

Before dedup: (116993, 3)
After dedup: (62718, 3)
label
1    34620
0    28098
Name: count, dtype: int64

In [7]:
import re

def clean_text(text):
    text = str(text)
    text = re.sub(r'^.*?\(Reuters\)\s*-\s*', '', text)
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

combined['clean_text'] = combined['text'].apply(clean_text)

# Shuffle
combined = combined.sample(frac=1, random_state=42).reset_index(drop=True)

print("Final dataset shape:", combined.shape)
combined.head()

Final dataset shape: (62718, 4)

,title,text,label,clean_text
0,Obama plan to stop tax inversions stirs U.S. b...,WASHINGTON (Reuters) - The Obama administratio...,1,The Obama administration’s plan to prevent Ame...
1,WATCH: Hypocrite Mitch McConnell Tells Democr...,"You know, because Republicans are now pretendi...",0,"You know, because Republicans are now pretendi..."
2,Trump questions U.S. financial backing for NATO,WASHINGTON (Reuters) - The United States shoul...,1,The United States should significantly cut spe...
3,"Canada G7 presidency to focus on women, gender...",OTTAWA (Reuters) - Canadian Prime Minister Jus...,1,"Canadian Prime Minister Justin Trudeau, who ha..."
4,Trump Expands Search for His Secretary of Stat...,WASHINGTON — Donald J. Trump is broadenin...,1,WASHINGTON — Donald J. Trump is broadening the...

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

X = combined['clean_text']
y = combined['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train size:", X_train.shape[0])
print("Test size:", X_test.shape[0])

vectorizer = TfidfVectorizer(max_df=0.7, min_df=5, stop_words='english', max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("TF-IDF matrix shape:", X_train_tfidf.shape)

Train size: 50174
Test size: 12544
TF-IDF matrix shape: (50174, 5000)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, y_train)

y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9244260204081632

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.90      0.91      5620
           1       0.92      0.94      0.93      6924

    accuracy                           0.92     12544
   macro avg       0.92      0.92      0.92     12544
weighted avg       0.92      0.92      0.92     12544


Confusion Matrix:
 [[5073  547]
 [ 401 6523]]

In [10]:
import joblib

joblib.dump(model, 'model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')

print("Updated model and vectorizer saved!")

Updated model and vectorizer saved!

In [1]:
try:
    print(combined.shape)
except NameError:
    print("Need to reload data")

Need to reload data

In [2]:
import pandas as pd
import re

fake = pd.read_csv('data/Fake.csv')
real = pd.read_csv('data/True.csv')
fake['label'] = 0
real['label'] = 1
original_df = pd.concat([fake[['title', 'text', 'label']], real[['title', 'text', 'label']]], ignore_index=True)

welfake = pd.read_csv('data/WELFake_Dataset.csv')
welfake = welfake.drop(columns=['Unnamed: 0'])
welfake['label'] = welfake['label'].map({0: 1, 1: 0})
welfake = welfake.dropna(subset=['text'])

combined = pd.concat([original_df, welfake[['title', 'text', 'label']]], ignore_index=True)
combined = combined.drop_duplicates(subset=['text'])

def clean_text(text):
    text = str(text)
    text = re.sub(r'^.*?\(Reuters\)\s*-\s*', '', text)
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

combined['clean_text'] = combined['text'].apply(clean_text)
combined = combined.sample(frac=1, random_state=42).reset_index(drop=True)

print("Reloaded:", combined.shape)

Reloaded: (62718, 4)

In [3]:
fake_subset = combined[combined['label'] == 0].sample(4000, random_state=42)
real_subset = combined[combined['label'] == 1].sample(4000, random_state=42)

subset = pd.concat([fake_subset, real_subset]).sample(frac=1, random_state=42).reset_index(drop=True)

print("Subset shape:", subset.shape)
print(subset['label'].value_counts())

Subset shape: (8000, 4)
label
0    4000
1    4000
Name: count, dtype: int64

In [4]:
from sklearn.model_selection import train_test_split

train_texts, test_texts, train_labels, test_labels = train_test_split(
    subset['clean_text'].tolist(),
    subset['label'].tolist(),
    test_size=0.2,
    random_state=42,
    stratify=subset['label']
)

print("Train size:", len(train_texts))
print("Test size:", len(test_texts))

Train size: 6400
Test size: 1600

In [5]:
from transformers import DistilBertTokenizerFast

tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=256)
test_encodings = tokenizer(test_texts, truncation=True, padding=True, max_length=256)

print("Tokenization done!")
print("Example input_ids length:", len(train_encodings['input_ids'][0]))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

C:\Users\Intern\Desktop\fake-news-detector\venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Intern\.cache\huggingface\hub\models--distilbert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Tokenization done!
Example input_ids length: 256

In [6]:
import torch
from transformers import DistilBertForSequenceClassification

class NewsDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = NewsDataset(train_encodings, train_labels)
test_dataset = NewsDataset(test_encodings, test_labels)

model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2)

print("Model loaded!")

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model loaded!

In [7]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir='./distilbert-results',
    num_train_epochs=2,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy='epoch',
    save_strategy='no',
    logging_steps=50,
    report_to='none'
)

def compute_metrics(eval_pred):
    from sklearn.metrics import accuracy_score, precision_recall_fscore_support
    predictions, labels = eval_pred
    predictions = predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average='binary')
    acc = accuracy_score(labels, predictions)
    return {'accuracy': acc, 'precision': precision, 'recall': recall, 'f1': f1}

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

print("Trainer ready!")

Trainer ready!

In [8]:
trainer.train()

C:\Users\Intern\Desktop\fake-news-detector\venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

KeyboardInterrupt:

In [9]:
fake_subset = combined[combined['label'] == 0].sample(1000, random_state=42)
real_subset = combined[combined['label'] == 1].sample(1000, random_state=42)

subset = pd.concat([fake_subset, real_subset]).sample(frac=1, random_state=42).reset_index(drop=True)

print("Subset shape:", subset.shape)

Subset shape: (2000, 4)

In [10]:
train_texts, test_texts, train_labels, test_labels = train_test_split(
    subset['clean_text'].tolist(),
    subset['label'].tolist(),
    test_size=0.2,
    random_state=42,
    stratify=subset['label']
)

train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=128)
test_encodings = tokenizer(test_texts, truncation=True, padding=True, max_length=128)

train_dataset = NewsDataset(train_encodings, train_labels)
test_dataset = NewsDataset(test_encodings, test_labels)

print("Train:", len(train_dataset), "Test:", len(test_dataset))

Train: 1600 Test: 400

In [11]:
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2)

training_args = TrainingArguments(
    output_dir='./distilbert-results',
    num_train_epochs=1,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy='epoch',
    save_strategy='no',
    logging_steps=20,
    report_to='none'
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
C:\Users\Intern\Desktop\fake-news-detector\venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

TrainOutput(global_step=200, training_loss=0.3015236496925354, metrics={'train_runtime': 1267.6572, 'train_samples_per_second': 1.262, 'train_steps_per_second': 0.158, 'total_flos': 52986959462400.0, 'train_loss': 0.3015236496925354, 'epoch': 1.0})

In [1]:
model.save_pretrained('./distilbert-fakenews-model')
tokenizer.save_pretrained('./distilbert-fakenews-model')

print("DistilBERT model saved!")

NameError: name 'model' is not defined

In [2]:
import pandas as pd
import re

fake = pd.read_csv('data/Fake.csv')
real = pd.read_csv('data/True.csv')
fake['label'] = 0
real['label'] = 1
original_df = pd.concat([fake[['title', 'text', 'label']], real[['title', 'text', 'label']]], ignore_index=True)

welfake = pd.read_csv('data/WELFake_Dataset.csv')
welfake = welfake.drop(columns=['Unnamed: 0'])
welfake['label'] = welfake['label'].map({0: 1, 1: 0})
welfake = welfake.dropna(subset=['text'])

combined = pd.concat([original_df, welfake[['title', 'text', 'label']]], ignore_index=True)
combined = combined.drop_duplicates(subset=['text'])

def clean_text(text):
    text = str(text)
    text = re.sub(r'^.*?\(Reuters\)\s*-\s*', '', text)
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

combined['clean_text'] = combined['text'].apply(clean_text)
combined = combined.sample(frac=1, random_state=42).reset_index(drop=True)

print("Reloaded:", combined.shape)

Reloaded: (62718, 4)

In [3]:
fake_subset = combined[combined['label'] == 0].sample(1000, random_state=42)
real_subset = combined[combined['label'] == 1].sample(1000, random_state=42)
subset = pd.concat([fake_subset, real_subset]).sample(frac=1, random_state=42).reset_index(drop=True)
print("Subset shape:", subset.shape)

Subset shape: (2000, 4)

In [4]:
from sklearn.model_selection import train_test_split
from transformers import DistilBertTokenizerFast

tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

train_texts, test_texts, train_labels, test_labels = train_test_split(
    subset['clean_text'].tolist(),
    subset['label'].tolist(),
    test_size=0.2,
    random_state=42,
    stratify=subset['label']
)

train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=128)
test_encodings = tokenizer(test_texts, truncation=True, padding=True, max_length=128)

print("Tokenized")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Tokenized

In [ ]:
import torch
from transformers import DistilBertForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

class NewsDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item
    def __len__(self):
        return len(self.labels)

train_dataset = NewsDataset(train_encodings, train_labels)
test_dataset = NewsDataset(test_encodings, test_labels)

model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2)

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average='binary')
    acc = accuracy_score(labels, predictions)
    return {'accuracy': acc, 'precision': precision, 'recall': recall, 'f1': f1}

training_args = TrainingArguments(
    output_dir='./distilbert-results',
    num_train_epochs=1,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy='epoch',
    save_strategy='no',
    logging_steps=20,
    report_to='none'
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
C:\Users\Intern\Desktop\fake-news-detector\venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

In [1]:
import pandas as pd
import re

fake = pd.read_csv('data/Fake.csv')
real = pd.read_csv('data/True.csv')
fake['label'] = 0
real['label'] = 1
original_df = pd.concat([fake[['title', 'text', 'label']], real[['title', 'text', 'label']]], ignore_index=True)

welfake = pd.read_csv('data/WELFake_Dataset.csv')
welfake = welfake.drop(columns=['Unnamed: 0'])
welfake['label'] = welfake['label'].map({0: 1, 1: 0})
welfake = welfake.dropna(subset=['text'])

combined = pd.concat([original_df, welfake[['title', 'text', 'label']]], ignore_index=True)
combined = combined.drop_duplicates(subset=['text'])

def clean_text(text):
    text = str(text)
    text = re.sub(r'^.*?\(Reuters\)\s*-\s*', '', text)
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

combined['clean_text'] = combined['text'].apply(clean_text)
combined = combined.sample(frac=1, random_state=42).reset_index(drop=True)

print("Reloaded:", combined.shape)

Reloaded: (62718, 4)

In [2]:
fake_subset = combined[combined['label'] == 0].sample(1000, random_state=42)
real_subset = combined[combined['label'] == 1].sample(1000, random_state=42)
subset = pd.concat([fake_subset, real_subset]).sample(frac=1, random_state=42).reset_index(drop=True)
print("Subset shape:", subset.shape)

Subset shape: (2000, 4)

In [3]:
from sklearn.model_selection import train_test_split
from transformers import DistilBertTokenizerFast

tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

train_texts, test_texts, train_labels, test_labels = train_test_split(
    subset['clean_text'].tolist(),
    subset['label'].tolist(),
    test_size=0.2,
    random_state=42,
    stratify=subset['label']
)

train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=128)
test_encodings = tokenizer(test_texts, truncation=True, padding=True, max_length=128)

print("Tokenized")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Tokenized

In [4]:
import torch
from transformers import DistilBertForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

class NewsDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item
    def __len__(self):
        return len(self.labels)

train_dataset = NewsDataset(train_encodings, train_labels)
test_dataset = NewsDataset(test_encodings, test_labels)

model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2)

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predictions, average='binary')
    acc = accuracy_score(labels, predictions)
    return {'accuracy': acc, 'precision': precision, 'recall': recall, 'f1': f1}

training_args = TrainingArguments(
    output_dir='./distilbert-results',
    num_train_epochs=1,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy='epoch',
    save_strategy='no',
    logging_steps=20,
    report_to='none'
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
C:\Users\Intern\Desktop\fake-news-detector\venv\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

TrainOutput(global_step=200, training_loss=0.28923306703567503, metrics={'train_runtime': 1090.1112, 'train_samples_per_second': 1.468, 'train_steps_per_second': 0.183, 'total_flos': 52986959462400.0, 'train_loss': 0.28923306703567503, 'epoch': 1.0})

In [5]:
model.save_pretrained('./distilbert-fakenews-model')
tokenizer.save_pretrained('./distilbert-fakenews-model')
print("DistilBERT model saved!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

DistilBERT model saved!